---

plugins:
  - jest
  - flowtype
  - babel

env:
  node: true
  jest: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:flowtype/recommended'

rules:
  no-console: 0
  linebreak-style: 0
  arrow-parens: ["error", "as-needed"]
  comma-dangle: 0
  function-paren-newline: ["error", "consistent"]